services:
  - type: web
    name: visual-data-science-dashboard
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: python -m pip install -U pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:server
